In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import train_test_split, KFold, cross_val_score

Using TensorFlow backend.


In [2]:
train_file_path = "../data/train.csv"
test_file_path = "../data/test.csv"

In [3]:
train_data = pd.read_csv(train_file_path)

In [4]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Unnamed: 0           3000 non-null   int64  
 1   光照强度                 3000 non-null   float64
 2   温度                   3000 non-null   float64
 3   globle optimal 电压    3000 non-null   float64
 4   corresponding power  3000 non-null   float64
dtypes: float64(4), int64(1)
memory usage: 117.3 KB


In [5]:
train_data[0:20]

Unnamed: 0    光照强度    温度  globle optimal 电压  corresponding power
0            1  233.44 -1.85         447.372202           857.662129
1            2  527.79 -1.44         450.233430          1959.204242
2            3  740.03 -1.02         450.333103          2748.355165
3            4  636.14 -0.24         449.950675          2361.292467
4            5  925.53  0.54         450.312536          3434.577357
5            6  642.25  1.32         449.742372          2383.241374
6            7  761.89  1.47         450.142277          2828.600926
7            8  552.73  1.63         449.691639          2050.409910
8            9  253.00  1.79         449.748726           933.185349
9           10   71.75  1.68         445.105320           255.779929
10          11   92.31  2.47         449.271336           332.347494
11          12  500.23  3.27         450.366641          1856.907893
12          13  247.80  3.77         449.698350           913.705202
13          14  729.57  4.27         450.511303          2710.275895
14          15  550.83  4.78         449.883283          2043.931073
15          16  739.74  4.73         450.360305          2747.390514
16          17  258.14  4.68         449.637343           952.259247
17          18  246.63  4.63         450.041355           909.695834
18          19   66.58  0.83         443.787691           236.635090
19          20  171.71  1.60         450.031302           629.514235

In [6]:
train_data_array = train_data.values

In [7]:
type(train_data_array)

numpy.ndarray

In [8]:
whole_data = train_data_array[:,1:]

In [9]:
whole_data.shape

(3000, 4)

In [10]:
data = whole_data[:,0:2]
label = whole_data[:,2:3]

In [11]:
data[0:5]

array([[ 2.3344e+02, -1.8500e+00],
       [ 5.2779e+02, -1.4400e+00],
       [ 7.4003e+02, -1.0200e+00],
       [ 6.3614e+02, -2.4000e-01],
       [ 9.2553e+02,  5.4000e-01]])

In [12]:
label[0:5]

array([[447.372202 ],
       [450.2334303],
       [450.3331029],
       [449.9506748],
       [450.3125364]])

In [13]:
X_train, X_test, Y_train, Y_test = train_test_split(data, label, test_size=0.3, random_state=0)

In [14]:
from keras.layers import Activation, Dense
from keras.optimizers import Adam
from keras.layers.normalization import BatchNormalization
model = Sequential()
model.add(Dense(128,input_dim=2))
model.add(BatchNormalization())
model.add(Activation('sigmoid'))
model.add(Dense(64))
model.add(BatchNormalization())
model.add(Activation('sigmoid'))
model.add(Dense(1))
adam = Adam(lr=0.01)
model.compile(loss='mse', optimizer=adam)

In [15]:
model.fit(X_train, Y_train, epochs=1000)

Epoch 1/1000
2100/2100 [==============================] - 1s 413us/step - loss: 177067.7199
Epoch 2/1000
2100/2100 [==============================] - 0s 29us/step - loss: 146880.7088
Epoch 3/1000
2100/2100 [==============================] - 0s 28us/step - loss: 111255.9807
Epoch 4/1000
2100/2100 [==============================] - 0s 27us/step - loss: 81119.9584
Epoch 5/1000
2100/2100 [==============================] - 0s 28us/step - loss: 58529.4657
Epoch 6/1000
2100/2100 [==============================] - 0s 27us/step - loss: 41785.8867
Epoch 7/1000
2100/2100 [==============================] - 0s 28us/step - loss: 29399.8692
Epoch 8/1000
2100/2100 [==============================] - 0s 27us/step - loss: 20336.7888
Epoch 9/1000
2100/2100 [==============================] - 0s 29us/step - loss: 13810.8613
Epoch 10/1000
2100/2100 [==============================] - 0s 28us/step - loss: 9202.8091
Epoch 11/1000
2100/2100 [==============================] - 0s 27us/step - loss: 6020.7373
Epoch 

2100/2100 [==============================] - 0s 29us/step - loss: 30.0087
Epoch 94/1000
2100/2100 [==============================] - 0s 28us/step - loss: 35.9380
Epoch 95/1000
2100/2100 [==============================] - 0s 28us/step - loss: 35.1619
Epoch 96/1000
2100/2100 [==============================] - 0s 29us/step - loss: 34.7987
Epoch 97/1000
2100/2100 [==============================] - 0s 28us/step - loss: 37.5887
Epoch 98/1000
2100/2100 [==============================] - 0s 26us/step - loss: 36.8687
Epoch 99/1000
2100/2100 [==============================] - 0s 28us/step - loss: 36.5732
Epoch 100/1000
2100/2100 [==============================] - 0s 27us/step - loss: 31.2442
Epoch 101/1000
2100/2100 [==============================] - 0s 29us/step - loss: 31.5175
Epoch 102/1000
2100/2100 [==============================] - 0s 28us/step - loss: 32.6779
Epoch 103/1000
2100/2100 [==============================] - 0s 28us/step - loss: 30.3062
Epoch 104/1000
2100/2100 [================

2100/2100 [==============================] - 0s 27us/step - loss: 26.9444
Epoch 186/1000
2100/2100 [==============================] - 0s 28us/step - loss: 24.6975
Epoch 187/1000
2100/2100 [==============================] - 0s 28us/step - loss: 28.3910
Epoch 188/1000
2100/2100 [==============================] - 0s 27us/step - loss: 27.6312
Epoch 189/1000
2100/2100 [==============================] - 0s 27us/step - loss: 32.6101
Epoch 190/1000
2100/2100 [==============================] - 0s 28us/step - loss: 30.2569
Epoch 191/1000
2100/2100 [==============================] - 0s 28us/step - loss: 23.9818
Epoch 192/1000
2100/2100 [==============================] - 0s 27us/step - loss: 23.9321
Epoch 193/1000
2100/2100 [==============================] - 0s 28us/step - loss: 27.8297
Epoch 194/1000
2100/2100 [==============================] - 0s 27us/step - loss: 28.3002
Epoch 195/1000
2100/2100 [==============================] - 0s 29us/step - loss: 28.9793
Epoch 196/1000
2100/2100 [==========

2100/2100 [==============================] - 0s 30us/step - loss: 31.0955
Epoch 278/1000
2100/2100 [==============================] - 0s 28us/step - loss: 24.3523
Epoch 279/1000
2100/2100 [==============================] - 0s 28us/step - loss: 26.4765
Epoch 280/1000
2100/2100 [==============================] - 0s 27us/step - loss: 28.4005
Epoch 281/1000
2100/2100 [==============================] - 0s 28us/step - loss: 23.3218
Epoch 282/1000
2100/2100 [==============================] - 0s 27us/step - loss: 27.9891
Epoch 283/1000
2100/2100 [==============================] - 0s 28us/step - loss: 26.2610
Epoch 284/1000
2100/2100 [==============================] - 0s 28us/step - loss: 20.8010
Epoch 285/1000
2100/2100 [==============================] - 0s 28us/step - loss: 25.1115
Epoch 286/1000
2100/2100 [==============================] - 0s 28us/step - loss: 24.3074
Epoch 287/1000
2100/2100 [==============================] - 0s 28us/step - loss: 24.4897
Epoch 288/1000
2100/2100 [==========

2100/2100 [==============================] - 0s 28us/step - loss: 23.3946
Epoch 370/1000
2100/2100 [==============================] - 0s 28us/step - loss: 24.9711
Epoch 371/1000
2100/2100 [==============================] - 0s 31us/step - loss: 24.0780
Epoch 372/1000
2100/2100 [==============================] - 0s 28us/step - loss: 21.1134
Epoch 373/1000
2100/2100 [==============================] - 0s 28us/step - loss: 22.3503
Epoch 374/1000
2100/2100 [==============================] - 0s 28us/step - loss: 23.5660
Epoch 375/1000
2100/2100 [==============================] - 0s 28us/step - loss: 19.3917
Epoch 376/1000
2100/2100 [==============================] - 0s 27us/step - loss: 25.4397
Epoch 377/1000
2100/2100 [==============================] - 0s 28us/step - loss: 26.3365
Epoch 378/1000
2100/2100 [==============================] - 0s 27us/step - loss: 20.2292
Epoch 379/1000
2100/2100 [==============================] - 0s 27us/step - loss: 25.8066
Epoch 380/1000
2100/2100 [==========

Epoch 461/1000
2100/2100 [==============================] - 0s 28us/step - loss: 22.0642
Epoch 462/1000
2100/2100 [==============================] - 0s 27us/step - loss: 22.2078
Epoch 463/1000
2100/2100 [==============================] - 0s 27us/step - loss: 25.3211
Epoch 464/1000
2100/2100 [==============================] - 0s 27us/step - loss: 20.2980
Epoch 465/1000
2100/2100 [==============================] - 0s 27us/step - loss: 22.5100
Epoch 466/1000
2100/2100 [==============================] - 0s 28us/step - loss: 20.7219
Epoch 467/1000
2100/2100 [==============================] - 0s 27us/step - loss: 22.5025
Epoch 468/1000
2100/2100 [==============================] - 0s 28us/step - loss: 22.7844
Epoch 469/1000
2100/2100 [==============================] - 0s 28us/step - loss: 22.0020
Epoch 470/1000
2100/2100 [==============================] - 0s 29us/step - loss: 22.7441
Epoch 471/1000
2100/2100 [==============================] - 0s 28us/step - loss: 22.4629
Epoch 472/1000
2100/2

2100/2100 [==============================] - 0s 28us/step - loss: 22.2943
Epoch 554/1000
2100/2100 [==============================] - 0s 28us/step - loss: 19.8152
Epoch 555/1000
2100/2100 [==============================] - 0s 28us/step - loss: 23.1467
Epoch 556/1000
2100/2100 [==============================] - 0s 29us/step - loss: 19.9253
Epoch 557/1000
2100/2100 [==============================] - 0s 28us/step - loss: 22.9543
Epoch 558/1000
2100/2100 [==============================] - 0s 28us/step - loss: 24.3018
Epoch 559/1000
2100/2100 [==============================] - 0s 32us/step - loss: 22.7563
Epoch 560/1000
2100/2100 [==============================] - 0s 31us/step - loss: 21.1543
Epoch 561/1000
2100/2100 [==============================] - 0s 30us/step - loss: 21.4113
Epoch 562/1000
2100/2100 [==============================] - 0s 29us/step - loss: 19.3849
Epoch 563/1000
2100/2100 [==============================] - 0s 28us/step - loss: 21.8269
Epoch 564/1000
2100/2100 [==========

2100/2100 [==============================] - 0s 29us/step - loss: 20.8344
Epoch 646/1000
2100/2100 [==============================] - 0s 30us/step - loss: 22.0451
Epoch 647/1000
2100/2100 [==============================] - 0s 30us/step - loss: 21.9461
Epoch 648/1000
2100/2100 [==============================] - 0s 29us/step - loss: 21.9026
Epoch 649/1000
2100/2100 [==============================] - 0s 28us/step - loss: 18.2219
Epoch 650/1000
2100/2100 [==============================] - 0s 27us/step - loss: 20.9997
Epoch 651/1000
2100/2100 [==============================] - 0s 28us/step - loss: 19.7665
Epoch 652/1000
2100/2100 [==============================] - 0s 28us/step - loss: 19.8508
Epoch 653/1000
2100/2100 [==============================] - 0s 28us/step - loss: 20.4221
Epoch 654/1000
2100/2100 [==============================] - 0s 27us/step - loss: 21.2359
Epoch 655/1000
2100/2100 [==============================] - 0s 28us/step - loss: 19.5609
Epoch 656/1000
2100/2100 [==========

2100/2100 [==============================] - 0s 29us/step - loss: 18.7516
Epoch 738/1000
2100/2100 [==============================] - 0s 28us/step - loss: 18.0865
Epoch 739/1000
2100/2100 [==============================] - 0s 28us/step - loss: 22.9021
Epoch 740/1000
2100/2100 [==============================] - 0s 27us/step - loss: 18.4880
Epoch 741/1000
2100/2100 [==============================] - 0s 28us/step - loss: 19.8917
Epoch 742/1000
2100/2100 [==============================] - 0s 28us/step - loss: 18.5419
Epoch 743/1000
2100/2100 [==============================] - 0s 29us/step - loss: 19.7233
Epoch 744/1000
2100/2100 [==============================] - 0s 28us/step - loss: 20.1074
Epoch 745/1000
2100/2100 [==============================] - 0s 28us/step - loss: 21.2689
Epoch 746/1000
2100/2100 [==============================] - 0s 29us/step - loss: 20.6845
Epoch 747/1000
2100/2100 [==============================] - 0s 28us/step - loss: 20.2698
Epoch 748/1000
2100/2100 [==========

Epoch 829/1000
2100/2100 [==============================] - 0s 30us/step - loss: 15.9869
Epoch 830/1000
2100/2100 [==============================] - 0s 28us/step - loss: 19.0832
Epoch 831/1000
2100/2100 [==============================] - 0s 28us/step - loss: 18.7195
Epoch 832/1000
2100/2100 [==============================] - 0s 28us/step - loss: 17.5535
Epoch 833/1000
2100/2100 [==============================] - 0s 27us/step - loss: 20.4668
Epoch 834/1000
2100/2100 [==============================] - 0s 28us/step - loss: 17.1357
Epoch 835/1000
2100/2100 [==============================] - 0s 28us/step - loss: 17.4020
Epoch 836/1000
2100/2100 [==============================] - 0s 28us/step - loss: 17.9120
Epoch 837/1000
2100/2100 [==============================] - 0s 29us/step - loss: 20.6008
Epoch 838/1000
2100/2100 [==============================] - 0s 28us/step - loss: 18.9093
Epoch 839/1000
2100/2100 [==============================] - 0s 28us/step - loss: 19.2097
Epoch 840/1000
2100/2

2100/2100 [==============================] - 0s 28us/step - loss: 19.2401
Epoch 921/1000
2100/2100 [==============================] - 0s 28us/step - loss: 20.2466
Epoch 922/1000
2100/2100 [==============================] - 0s 29us/step - loss: 18.2243
Epoch 923/1000
2100/2100 [==============================] - 0s 29us/step - loss: 19.7215
Epoch 924/1000
2100/2100 [==============================] - 0s 28us/step - loss: 19.1534
Epoch 925/1000
2100/2100 [==============================] - 0s 28us/step - loss: 24.7504
Epoch 926/1000
2100/2100 [==============================] - 0s 28us/step - loss: 19.4638
Epoch 927/1000
2100/2100 [==============================] - 0s 28us/step - loss: 17.0001
Epoch 928/1000
2100/2100 [==============================] - 0s 29us/step - loss: 20.1963
Epoch 929/1000
2100/2100 [==============================] - 0s 28us/step - loss: 17.9396
Epoch 930/1000
2100/2100 [==============================] - 0s 28us/step - loss: 18.3744
Epoch 931/1000
2100/2100 [==========

In [16]:
predictions = model.predict(X_test)

In [17]:
total_rate = 0
for i in range(900):
    rate = predictions[i]/Y_test[i]
    total_rate = total_rate + rate
print(total_rate/900)

[0.98708343]


In [18]:
model.save('second_model.h5')

In [19]:
test_data = pd.read_csv(test_file_path)

In [20]:
test_data_array = test_data.values

In [21]:
test_data_array[0:20]

array([[1.0000000e+00, 3.8410000e+01, 2.4400000e+01, 4.2581699e+02,
                  nan],
       [2.0000000e+00, 3.3840000e+01, 1.9350000e+01, 4.2263586e+02,
                  nan],
       [3.0000000e+00, 2.2979000e+02, 1.9300000e+01, 4.3681961e+02,
                  nan],
       [4.0000000e+00, 4.7031000e+02, 2.0480000e+01, 4.3791934e+02,
                  nan],
       [5.0000000e+00, 6.9583000e+02, 2.1660000e+01, 4.4029410e+02,
                  nan],
       [6.0000000e+00, 8.7644000e+02, 2.2840000e+01, 4.4152261e+02,
                  nan],
       [7.0000000e+00, 9.9145000e+02, 2.3330000e+01, 4.4213275e+02,
                  nan],
       [8.0000000e+00, 1.0313700e+03, 2.3810000e+01, 4.4238544e+02,
                  nan],
       [9.0000000e+00, 9.9280000e+02, 2.4300000e+01, 4.4236288e+02,
                  nan],
       [1.0000000e+01, 6.9569000e+02, 2.4290000e+01, 4.4079788e+02,
                  nan],
       [1.1000000e+01, 6.9985000e+02, 2.4280000e+01, 4.4083322e+02,
            

In [22]:
whole_test_data = test_data_array[:,1:3]

In [23]:
whole_test_data[0:20]

array([[  38.41,   24.4 ],
       [  33.84,   19.35],
       [ 229.79,   19.3 ],
       [ 470.31,   20.48],
       [ 695.83,   21.66],
       [ 876.44,   22.84],
       [ 991.45,   23.33],
       [1031.37,   23.81],
       [ 992.8 ,   24.3 ],
       [ 695.69,   24.29],
       [ 699.85,   24.28],
       [ 475.06,   24.27],
       [ 234.92,   23.91],
       [  37.  ,   23.55],
       [  33.48,   18.63],
       [ 228.69,   18.8 ],
       [ 468.29,   19.86],
       [ 693.89,   20.92],
       [ 874.61,   21.98],
       [ 989.64,   22.42]])

In [24]:
predict_test_data = model.predict(whole_test_data)

In [25]:
predict_test_data.shape

(1000, 1)

In [26]:
predict_test_data[0:20]

array([[409.59146],
       [408.31644],
       [428.3536 ],
       [433.9188 ],
       [434.0222 ],
       [433.04175],
       [432.24796],
       [431.14383],
       [430.17474],
       [430.62088],
       [430.6468 ],
       [429.03946],
       [421.15817],
       [409.60117],
       [408.8079 ],
       [428.92673],
       [434.3062 ],
       [434.57303],
       [434.32935],
       [434.04013]], dtype=float32)

In [27]:
import numpy
data = pd.DataFrame(predict_test_data)
writer = pd.ExcelWriter('second_predict_test_data.xlsx')
data.to_excel(writer, 'page_1', float_format='%.5f')
writer.save()
writer.close()